=== MaicoSautner/l2script-teste/dist/gameserver/data/skill_tree/tree.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT list (general_skill_tree|sub_unit_skill_tree|pledge_skill_tree|collection_skill_tree|certification_skill_tree|dual_certification_skill_tree|transfer_skill_tree|normal_skill_tree|chaos_skill_tree|dual_chaos_skill_tree|dual_class_skill_tree|fishing_skill_tree|transformation_skill_tree|awake_parent_skill_tree|noblesse_skill_tree|hero_skill_tree|gm_skill_tree|custom_skill_tree|ability_skill_tree|abilities_settings|alchemy_skill_tree|honor_noblesse_skill_tree)*>
<!ELEMENT general_skill_tree (skill|class)*>
<!ELEMENT transfer_skill_tree (class)*>
<!ELEMENT normal_skill_tree (class)*>
<!ELEMENT dual_class_skill_tree (class)*>
<!ELEMENT awake_parent_skill_tree (awake_class)*>
<!ELEMENT sub_unit_skill_tree (skill)*>
<!ELEMENT pledge_skill_tree (skill)*>
<!ELEMENT collection_skill_tree (skill)*>
<!ELEMENT certification_skill_tree (skill)*>
<!ELEMENT dual_certification_skill_tree (skill)*>
<!ELEMENT fishing_skill_tree (skill)*>
<!ELEMENT transformation_skill_tree (skill)*>
<!ELEMENT chaos_skill_tree (skill)*>
<!ELEMENT dual_chaos_skill_tree (skill)*>
<!ELEMENT noblesse_skill_tree (skill)*>
<!ELEMENT hero_skill_tree (skill)*>
<!ELEMENT gm_skill_tree (skill)*>
<!ELEMENT custom_skill_tree (skill)*>
<!ELEMENT ability_skill_tree (skill)*>
<!ELEMENT alchemy_skill_tree (skill)*>
<!ELEMENT honor_noblesse_skill_tree (skill)*>
	<!ELEMENT skill (player|or|not|and)*>
		<!ATTLIST skill
			id CDATA #REQUIRED
			item_count CDATA #IMPLIED
			item_id CDATA #IMPLIED
			level CDATA #REQUIRED
			min_level CDATA #IMPLIED
			name CDATA #IMPLIED
			cost CDATA #IMPLIED
			race CDATA #IMPLIED
			auto_get CDATA #IMPLIED
			dual_class_min_level CDATA #IMPLIED>
			
			<!ELEMENT or (player|or|not|and)*>
			<!ELEMENT not (player|or|not|and)*>
			<!ELEMENT and (player|or|not|and)*>
			<!ELEMENT player (#PCDATA)>
			<!ATTLIST player
				residence CDATA #IMPLIED
				olympiad CDATA #IMPLIED
				race CDATA #IMPLIED
				instance_zone CDATA #IMPLIED
				is_clan_leader CDATA #IMPLIED
				sex CDATA #IMPLIED
				castle_type CDATA #IMPLIED
				classId CDATA #IMPLIED
				minLevel CDATA #IMPLIED
				max_level CDATA #IMPLIED
				avail_max_sp CDATA #IMPLIED
				chaos_festival CDATA #IMPLIED
				quest_state CDATA #IMPLIED
				min_pledge_rank CDATA #IMPLIED
				class_type CDATA #IMPLIED
				min_clan_level CDATA #IMPLIED
				isFlagged CDATA #IMPLIED
				is_hero CDATA #IMPLIED>

	<!ELEMENT class (skill)*>
		<!ATTLIST class
			id CDATA #IMPLIED
			level CDATA #IMPLIED>

	<!ELEMENT awake_class (parent_class)*>
		<!ATTLIST awake_class id CDATA #REQUIRED>

		<!ELEMENT parent_class (skill)*>
			<!ATTLIST parent_class id CDATA #REQUIRED>

<!ELEMENT abilities_settings (#PCDATA)*>
	<!ATTLIST abilities_settings
		min_level CDATA #REQUIRED
		maximun_points CDATA #REQUIRED
		refresh_price CDATA #REQUIRED>

=== MaicoSautner/l2script-teste/dist/gameserver/data/skill_tree/awake_parent_skill_tree/[140] tyr_warrior.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "tree.dtd">
<!--Create by VISTALL. Full reworked to Glory of Destruction by Bonux. -->
<list>
	<awake_parent_skill_tree>
		<awake_class id="140">	<!--Воин Тира-->
			<parent_class id="88"> <!--Дуэлист-->
				<skill id="87" level="1" name="Найти Уязвимость Животных"/>
				<skill id="104" level="1" name="Найти Уязвимость Растений"/>
				<skill id="80" level="1" name="Найти Уязвимость Чудовищ"/>
				<skill id="88" level="1" name="Найти Уязвимость Драконов"/>
				<skill id="451" level="2" name="Звуковое Движение"/>
				<skill id="297" level="2" name="Дух Дуэлянта"/>
				<skill id="5" level="31" name="Двойной Звуковой Разрез"/>
				<skill id="144" level="37" name="Владение Парным Оружием"/>
				<skill id="227" level="50" name="Владение Легкой Броней"/>
				<skill id="9" level="34" name="Звуковая Волна"/>
				<skill id="7" level="33" name="Звуковой Шторм(Sonic Storm)"/>
				<skill id="257" level="45" name="Владение Мечом/Дробящим Оружием"/>
				<skill id="261" level="27" name="Тройное Звуковое Рассечение(Triple Sonic Slash)"/>
				<skill id="1" level="37" name="Тройное Рассечение"/>
				<skill id="290" level="14" name="Предельное Безумие"/>
				<skill id="212" level="8" name="Быстрое Восстановление HP"/>
				<skill id="190" level="37" name="Фатальный Удар"/>
				<skill id="260" level="37" name="Сокрушение Молотом"/>
				<skill id="231" level="50" name="Владение Тяжелой Броней"/>
				<skill id="328" level="1" name="Мудрость"/>
				<skill id="329" level="1" name="Здоровье"/>
				<skill id="330" level="1" name="Владение Умениями"/>
				<skill id="359" level="1" name="Глаз Охотника"/>
				<skill id="345" level="4" name="Гнев Звука"/>
				<skill id="360" level="1" name="Глаз Убийцы"/>
				<skill id="992" level="8" name="Владение Звуком"/>
				<skill id="442" level="1" name="Звуковой Барьер"/>
				<skill id="8" level="8" name="Фокусировка Звука"/>
				<skill id="775" level="1" name="Блокировка Оружия"/>
				<skill id="995" level="1" name="Стремительный Натиск"/>
				<skill id="430" level="4" name="Мастер Схватки"/>
			</parent_class>
			<parent_class id="89"> <!--Полководец-->
				<skill id="87" level="1" name="Найти Уязвимость Животных"/>
				<skill id="104" level="1" name="Найти Уязвимость Растений"/>
				<skill id="80" level="1" name="Найти Уязвимость Чудовищ"/>
				<skill id="181" level="1" name="Возрождение"/>
				<skill id="130" level="2" name="Волнующая Схватка"/>
				<skill id="88" level="1" name="Найти Уязвимость Драконов"/>
				<skill id="286" level="8" name="Провоцировать"/>
				<skill id="121" level="6" name="Боевой Рев"/>
				<skill id="452" level="5" name="Оглушающий Топот"/>
				<skill id="227" level="50" name="Владение Легкой Броней"/>
				<skill id="211" level="10" name="Увеличение HP"/>
				<skill id="36" level="37" name="Вихрь"/>
				<skill id="48" level="42" name="Грозовой Шторм"/>
				<skill id="421" level="5" name="Свирепое Нападение"/>
				<skill id="920" level="37" name="Сокрушительная Мощь"/>
				<skill id="290" level="14" name="Предельное Безумие"/>
				<skill id="212" level="8" name="Быстрое Восстановление HP"/>
				<skill id="317" level="5" name="Фокусировка Атаки"/>
				<skill id="216" level="45" name="Владение Древковым Оружием"/>
				<skill id="422" level="3" name="Точность Копья"/>
				<skill id="116" level="14" name="Вой"/>
				<skill id="231" level="50" name="Владение Тяжелой Броней"/>
				<skill id="921" level="1" name="Острие Иглы"/>
				<skill id="328" level="1" name="Мудрость"/>
				<skill id="329" level="1" name="Здоровье"/>
				<skill id="330" level="1" name="Владение Умениями"/>
				<skill id="359" level="1" name="Глаз Охотника"/>
				<skill id="360" level="1" name="Глаз Убийцы"/>
				<skill id="347" level="1" name="Землетрясение"/>
				<skill id="995" level="1" name="Стремительный Натиск"/>
				<skill id="320" level="10" name="Гнев"/>
			</parent_class>
			<parent_class id="113"> <!--Титан--><!--Checked offlike: 04.02.2016-->
				<skill id="176" level="5" name="Безумие"/>
				<skill id="34" level="3" name="Перевязка"/>
				<skill id="121" level="6" name="Боевой Рев"/>
				<skill id="148" level="8" name="Жизненная Сила"/>
				<skill id="227" level="50" name="Владение Легкой Броней"/>
				<skill id="211" level="10" name="Увеличение HP"/>
				<skill id="257" level="45" name="Владение Мечом/Дробящим Оружием"/>
				<skill id="36" level="37" name="Вихрь"/>
				<skill id="423" level="3" name="Инфернальный Вид"/>
				<skill id="315" level="16" name="Сокрушение Судьбы"/>
				<skill id="293" level="20" name="Владение Двуручным Оружием"/>
				<skill id="212" level="8" name="Быстрое Восстановление HP"/>
				<skill id="190" level="37" name="Фатальный Удар"/>
				<skill id="216" level="45" name="Владение Древковым Оружием"/>
				<skill id="422" level="3" name="Точность Копья"/>
				<skill id="260" level="37" name="Сокрушение Молотом"/>
				<skill id="231" level="50" name="Владение Тяжелой Броней"/>
				<skill id="328" level="1" name="Мудрость"/>
				<skill id="335" level="1" name="Стойкость"/>
				<skill id="329" level="1" name="Здоровье"/>
				<skill id="330" level="1" name="Владение Умениями"/>
				<skill id="362" level="1" name="Пролом Брони"/>
				<skill id="347" level="1" name="Землетрясение"/>
				<skill id="995" level="1" name="Стремительный Натиск"/>
				<skill id="139" level="5" name="Мужество"/>
				<skill id="94" level="4" name="Гнев"/>
			</parent_class>
			<parent_class id="114"> <!--Аватар-->
				<skill id="319" level="2" name="Быстрое Перемещение"/>
				<skill id="282" level="1" name="Тотемный Дух Пумы"/>
				<skill id="109" level="1" name="Тотемный Дух Огра"/>
				<skill id="168" level="3" name="Увеличить Скорость Атаки"/>
				<skill id="298" level="1" name="Тотемный Дух Кролика"/>
				<skill id="292" level="1" name="Тотемный Дух Бизона"/>
				<skill id="81" level="3" name="Удар Судьбы"/>
				<skill id="233" level="47" name="Владение Легкой Броней"/>
				<skill id="280" level="37" name="Горящий Кулак"/>
				<skill id="281" level="37" name="Разрушитель Душ"/>
				<skill id="423" level="3" name="Инфернальный Вид"/>
				<skill id="95" level="20" name="Хромота"/>
				<skill id="425" level="1" name="Тотемный Дух Ястреба"/>
				<skill id="17" level="34" name="Взрыв Силы"/>
				<skill id="35" level="33" name="Силовой Шторм"/>
				<skill id="210" level="45" name="Владение Кастетами"/>
				<skill id="284" level="40" name="Ураганное Нападение"/>
				<skill id="328" level="1" name="Мудрость"/>
				<skill id="329" level="1" name="Здоровье"/>
				<skill id="330" level="1" name="Владение Умениями"/>
				<skill id="346" level="4" name="Гнев Силы"/>
				<skill id="441" level="1" name="Силовая Медитация"/>
				<skill id="993" level="8" name="Владение Силой"/>
				<skill id="443" level="1" name="Силовой Барьер"/>
				<skill id="50" level="8" name="Фокусировка Силы"/>
				<skill id="995" level="1" name="Стремительный Натиск"/>
				<skill id="222" level="3" name="Ярость Орка"/>
			</parent_class>
			<parent_class id="118"> <!--Мастер-->
				<skill id="822" level="3" name="Починка Голема"/>
				<skill id="824" level="3" name="Бронепластина"/>
				<skill id="823" level="3" name="Усиление Голема"/>
				<skill id="34" level="3" name="Перевязка"/>
				<skill id="1561" level="5" name="Боевой Клич"/>
				<skill id="248" level="5" name="Кристаллизация"/>
				<skill id="172" level="10" name="Создать Вещь"/>
				<skill id="148" level="8" name="Жизненная Сила"/>
				<skill id="25" level="9" name="Призвать Механического Голема"/>
				<skill id="227" level="50" name="Владение Легкой Броней"/>
				<skill id="211" level="10" name="Увеличение HP"/>
				<skill id="301" level="5" name="Призвать Гулкий Рокот"/>
				<skill id="205" level="45" name="Владение Мечом/Дробящим Оружием"/>
				<skill id="36" level="37" name="Вихрь"/>
				<skill id="212" level="8" name="Быстрое Восстановление HP"/>
				<skill id="190" level="37" name="Фатальный Удар"/>
				<skill id="216" level="45" name="Владение Древковым Оружием"/>
				<skill id="422" level="3" name="Точность Копья"/>
				<skill id="260" level="37" name="Сокрушение Молотом"/>
				<skill id="231" level="50" name="Владение Тяжелой Броней"/>
				<skill id="328" level="1" name="Мудрость"/>
				<skill id="329" level="1" name="Здоровье"/>
				<skill id="330" level="1" name="Владение Умениями"/>
				<skill id="362" level="1" name="Пролом Брони"/>
				<skill id="347" level="1" name="Землетрясение"/>
				<skill id="995" level="1" name="Стремительный Натиск"/>
			</parent_class>
			<parent_class id="131"> <!--Каратель-->
				<skill id="481" level="2" name="Броня Тьмы"/>
				<skill id="832" level="1" name="Быстрое Восстановление"/>
				<skill id="833" level="1" name="Восстановление Тела"/>
				<skill id="1514" level="3" name="Преграда Душ"/>
				<skill id="20006" level="1" name="Рев Душ"/>
				<skill id="503" level="3" name="Презрение"/>
				<skill id="1510" level="1" name="Искупление Души"/>
				<skill id="477" level="37" name="Сокрушение Тьмой"/>
				<skill id="465" level="50" name="Владение Легкой Броней"/>
				<skill id="501" level="12" name="Дурной Характер"/>
				<skill id="496" level="31" name="Режущий Клинок"/>
				<skill id="492" level="25" name="Расправить Крылья"/>
				<skill id="472" level="45" name="Владение Древним Мечом"/>
				<skill id="498" level="12" name="Инфекция"/>
				<skill id="497" level="16" name="Сокрушающая Боль"/>
				<skill id="328" level="1" name="Мудрость"/>
				<skill id="329" level="1" name="Здоровье"/>
				<skill id="330" level="1" name="Владение Умениями"/>
				<skill id="793" level="1" name="Стремительный Натиск"/>
				<skill id="939" level="1" name="Гнев Души"/>
				<skill id="526" level="1" name="Энума Элиш"/>
				<skill id="794" level="1" name="Массовое Разоружение"/>
				<skill id="483" level="4" name="Защититься Мечом"/>
				<skill id="485" level="12" name="Разоружить"/>
			</parent_class>
		</awake_class>
	</awake_parent_skill_tree>
</list>

=== MaicoSautner/l2script-teste/dist/gameserver/data/skill_tree/normal_skill_tree/[185] saiha_mage.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "tree.dtd">
<!--AUTHOR: Bonux-->
<list>
	<normal_skill_tree>
		<class id="185">	<!--Последователь Сайхи-->
			<!--Default by level skills-->
			<skill id="30004" level="1" name="Водяной Удар(Hydro Strike)" cost="45" min_level="40"/>
			<skill id="17920" level="1" name="Зелье Исцеления Ветра(Windy Healing Potion)" min_level="40"/>
			<skill id="30017" level="1" name="Идеальный Шторм(Squall)" cost="45" min_level="40"/>
			<skill id="30012" level="1" name="Натиск Ветра(Air Rush)" cost="45" min_level="40"/>
			<skill id="30016" level="1" name="Око Шторма(Eye of the Storm)" cost="45" min_level="40"/>
			<skill id="17943" level="1" name="Перегонный Куб(Alchemy Cube)" min_level="40"/>
			<skill id="30042" level="2" name="Превосходная Перезарядка(Eminent Quick Recovery)" cost="45" min_level="40"/>
			<skill id="30040" level="3" name="Превосходное Владение Дробящим Оружием(Eminent Blunt Weapon Mastery)" cost="45" min_level="40"/>
			<skill id="30041" level="3" name="Превосходное Владение Магической Броней(Eminent Robe Mastery)" cost="45" min_level="40"/>
			<skill id="30045" level="1" name="Превосходные Способности(Eminent Ability)" cost="45" min_level="40"/>
			<skill id="30001" level="5" name="Водная Атака(Hydro Attack)" cost="51" min_level="42"/>
			<skill id="30004" level="2" name="Водяной Удар(Hydro Strike)" cost="56" min_level="44"/>
			<skill id="30012" level="2" name="Натиск Ветра(Air Rush)" cost="56" min_level="44"/>
			<skill id="30001" level="6" name="Водная Атака(Hydro Attack)" cost="78" min_level="46"/>
			<skill id="30004" level="3" name="Водяной Удар(Hydro Strike)" cost="101" min_level="48"/>
			<skill id="30012" level="3" name="Натиск Ветра(Air Rush)" cost="101" min_level="48"/>
			<skill id="30001" level="7" name="Водная Атака(Hydro Attack)" cost="123" min_level="50"/>
			<skill id="1405" level="1" name="Божественное Вдохновение(Divine Inspiration)" cost="144" min_level="52"/>
			<skill id="30004" level="4" name="Водяной Удар(Hydro Strike)" cost="144" min_level="52"/>
			<skill id="30012" level="4" name="Натиск Ветра(Air Rush)" cost="144" min_level="52"/>
			<skill id="30040" level="4" name="Превосходное Владение Дробящим Оружием(Eminent Blunt Weapon Mastery)" cost="144" min_level="52"/>
			<skill id="30041" level="4" name="Превосходное Владение Магической Броней(Eminent Robe Mastery)" cost="144" min_level="52"/>
			<skill id="30001" level="8" name="Водная Атака(Hydro Attack)" cost="152" min_level="54"/>
			<skill id="30004" level="5" name="Водяной Удар(Hydro Strike)" cost="158" min_level="56"/>
			<skill id="30012" level="5" name="Натиск Ветра(Air Rush)" cost="158" min_level="56"/>
			<skill id="30004" level="6" name="Водяной Удар(Hydro Strike)" cost="227" min_level="58"/>
			<skill id="30012" level="6" name="Натиск Ветра(Air Rush)" cost="227" min_level="58"/>
			<skill id="30004" level="6" name="Водяной Удар(Hydro Strike)" cost="227" min_level="60"/>
			<skill id="30012" level="6" name="Натиск Ветра(Air Rush)" cost="227" min_level="60"/>
			<skill id="1405" level="2" name="Божественное Вдохновение(Divine Inspiration)" cost="294" min_level="61"/>
			<skill id="30001" level="10" name="Водная Атака(Hydro Attack)" cost="301" min_level="62"/>
			<skill id="30003" level="2" name="Ледяная Вспышка(Hydro Flare)" cost="301" min_level="62"/>
			<skill id="30004" level="7" name="Водяной Удар(Hydro Strike)" cost="315" min_level="64"/>
			<skill id="30012" level="7" name="Натиск Ветра(Air Rush)" cost="315" min_level="64"/>
			<skill id="30040" level="5" name="Превосходное Владение Дробящим Оружием(Eminent Blunt Weapon Mastery)" cost="315" min_level="64"/>
			<skill id="30041" level="5" name="Превосходное Владение Магической Броней(Eminent Robe Mastery)" cost="315" min_level="64"/>
			<skill id="30001" level="11" name="Водная Атака(Hydro Attack)" cost="515" min_level="66"/>
			<skill id="30003" level="3" name="Ледяная Вспышка(Hydro Flare)" cost="515" min_level="66"/>
			<skill id="30004" level="8" name="Водяной Удар(Hydro Strike)" cost="717" min_level="68"/>
			<skill id="30012" level="8" name="Натиск Ветра(Air Rush)" cost="717" min_level="68"/>
			<skill id="30001" level="12" name="Водная Атака(Hydro Attack)" cost="919" min_level="70"/>
			<skill id="30003" level="4" name="Ледяная Вспышка(Hydro Flare)" cost="919" min_level="70"/>
			<skill id="30004" level="9" name="Водяной Удар(Hydro Strike)" cost="1122" min_level="72"/>
			<skill id="30012" level="9" name="Натиск Ветра(Air Rush)" cost="1122" min_level="72"/>
			<skill id="30001" level="13" name="Водная Атака(Hydro Attack)" cost="1686" min_level="74"/>
			<skill id="30003" level="5" name="Ледяная Вспышка(Hydro Flare)" cost="1686" min_level="74"/>
		</class>
	</normal_skill_tree>
</list>

=== MaicoSautner/l2script-teste/dist/gameserver/data/skill_tree/normal_skill_tree/[186] ranger.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "tree.dtd">
<!--AUTHOR: Bonux-->
<list>
	<normal_skill_tree>
		<class id="186">	<!--Ловец Ветра-->
			<!--Default by level skills-->
			<skill id="1405" level="3" name="Божественное Вдохновение(Divine Inspiration)" cost="3000" min_level="76"/>
			<skill id="1405" level="4" name="Божественное Вдохновение(Divine Inspiration)" cost="3000" min_level="76"/>
			<skill id="30504" level="1" name="Встречный Ветер Гравитации(Gravity Hit)" cost="3000" min_level="76"/>
			<skill id="30530" level="1" name="Искажение Энергии(Crushing Air)" cost="3000" min_level="76"/>
			<skill id="30542" level="3" name="Превосходная Устойчивость(Eminent Stability)" cost="3000" min_level="76"/>
			<skill id="30540" level="6" name="Превосходное Владение Кастетами(Eminent Fist Weapon Mastery)" cost="3000" min_level="76"/>
			<skill id="30541" level="6" name="Превосходное Владение Легкими Доспехами(Eminent Light Armor Mastery)" cost="3000" min_level="76"/>
			<skill id="30544" level="1" name="Превосходное Сопротивление Отрицательным Эффектам(Eminent Trait Resistance)" cost="3000" min_level="76"/>
			<skill id="30543" level="1" name="Превосходное Сопротивление Стихиям(Eminent Attribute Resistance)" cost="3000" min_level="76"/>
			<skill id="30545" level="2" name="Превосходные Способности(Eminent Ability)" cost="3000" min_level="76"/>
			<skill id="30512" level="1" name="Преображение(Distortion)" cost="3000" min_level="76"/>
			<skill id="30526" level="1" name="Удар Гравитации(Heavy Punch)" cost="3000" min_level="76"/>
			<skill id="30502" level="10" name="Удар с Рассечением(Chin Strike)" cost="3000" min_level="76"/>
			<skill id="30507" level="10" name="Шаг Влево(Left Sidestep)" cost="3000" min_level="76"/>
			<skill id="30509" level="1" name="Шаг Назад(Back Step)" cost="3000" min_level="76"/>
			<skill id="30500" level="14" name="Боковая Атака(Lateral Hit)" cost="4500" min_level="77"/>
			<skill id="30501" level="13" name="Удар с Разворота(Backspin Blow)" cost="4500" min_level="77"/>
			<skill id="30508" level="13" name="Шаг Вправо(Right Sidestep)" cost="4500" min_level="77"/>
			<skill id="30504" level="2" name="Встречный Ветер Гравитации(Gravity Hit)" cost="6000" min_level="78"/>
			<skill id="30530" level="2" name="Искажение Энергии(Crushing Air)" cost="6000" min_level="78"/>
			<skill id="30502" level="11" name="Удар с Рассечением(Chin Strike)" cost="6000" min_level="78"/>
			<skill id="30507" level="11" name="Шаг Влево(Left Sidestep)" cost="6000" min_level="78"/>
			<skill id="30500" level="15" name="Боковая Атака(Lateral Hit)" cost="7500" min_level="79"/>
			<skill id="30506" level="1" name="Удар Ногой в Голову с Разворота(Distant Kick)" cost="7500" min_level="79"/>
			<skill id="30501" level="14" name="Удар с Разворота(Backspin Blow)" cost="7500" min_level="79"/>
			<skill id="30508" level="14" name="Шаг Вправо(Right Sidestep)" cost="7500" min_level="79"/>
			<skill id="30504" level="3" name="Встречный Ветер Гравитации(Gravity Hit)" cost="9000" min_level="80"/>
			<skill id="30530" level="3" name="Искажение Энергии(Crushing Air)" cost="9000" min_level="80"/>
			<skill id="30540" level="7" name="Превосходное Владение Кастетами(Eminent Fist Weapon Mastery)" cost="9000" min_level="80"/>
			<skill id="30541" level="7" name="Превосходное Владение Легкими Доспехами(Eminent Light Armor Mastery)" cost="9000" min_level="80"/>
			<skill id="30502" level="12" name="Удар с Рассечением(Chin Strike)" cost="9000" min_level="80"/>
			<skill id="30507" level="12" name="Шаг Влево(Left Sidestep)" cost="9000" min_level="80"/>
			<skill id="30500" level="16" name="Боковая Атака(Lateral Hit)" cost="10500" min_level="81"/>
			<skill id="30506" level="2" name="Удар Ногой в Голову с Разворота(Distant Kick)" cost="10500" min_level="81"/>
			<skill id="30501" level="15" name="Удар с Разворота(Backspin Blow)" cost="10500" min_level="81"/>
			<skill id="30508" level="15" name="Шаг Вправо(Right Sidestep)" cost="10500" min_level="81"/>
			<skill id="30504" level="4" name="Встречный Ветер Гравитации(Gravity Hit)" cost="12000" min_level="82"/>
			<skill id="30530" level="4" name="Искажение Энергии(Crushing Air)" cost="12000" min_level="82"/>
			<skill id="30502" level="13" name="Удар с Рассечением(Chin Strike)" cost="12000" min_level="82"/>
			<skill id="30507" level="13" name="Шаг Влево(Left Sidestep)" cost="12000" min_level="82"/>
			<skill id="30500" level="17" name="Боковая Атака(Lateral Hit)" cost="13125" min_level="83"/>
			<skill id="30506" level="3" name="Удар Ногой в Голову с Разворота(Distant Kick)" cost="13125" min_level="83"/>
			<skill id="30501" level="16" name="Удар с Разворота(Backspin Blow)" cost="13125" min_level="83"/>
			<skill id="30508" level="16" name="Шаг Вправо(Right Sidestep)" cost="13125" min_level="83"/>
			<skill id="30504" level="5" name="Встречный Ветер Гравитации(Gravity Hit)" cost="14250" min_level="84"/>
			<skill id="30530" level="5" name="Искажение Энергии(Crushing Air)" cost="14250" min_level="84"/>
			<skill id="30502" level="14" name="Удар с Рассечением(Chin Strike)" cost="14250" min_level="84"/>
			<skill id="30507" level="14" name="Шаг Влево(Left Sidestep)" cost="14250" min_level="84"/>
		</class>
	</normal_skill_tree>
</list>
