=== MaicoSautner/l2script-teste/dist/gameserver/data/skills/skill.dtd
<!ELEMENT list (skill)*>

	<!ELEMENT skill  (set|table|for|cond|triggers|enchant_info|restoration)*>
	<!ATTLIST skill
		id CDATA #REQUIRED
		levels CDATA #REQUIRED
		name CDATA #REQUIRED>

		<!ELEMENT set (player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST set
			name CDATA #IMPLIED
			order CDATA #IMPLIED
			stat CDATA #IMPLIED
			value CDATA #REQUIRED>

		<!ELEMENT table (#PCDATA)>
		<!ATTLIST table
			name CDATA #REQUIRED
			type CDATA #IMPLIED>

		<!ELEMENT start_effect (def|add|p_attack_trait|p_defence_trait|set|mul|div|sub|cond|triggers|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST start_effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			interval CDATA #IMPLIED
			instant CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED>

		<!ELEMENT tick_effect (def|add|p_attack_trait|p_defence_trait|set|mul|div|sub|cond|triggers|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST tick_effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			interval CDATA #IMPLIED
			instant CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED>

		<!ELEMENT self_effect (def|add|p_attack_trait|p_defence_trait|set|mul|div|sub|cond|triggers|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST self_effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			interval CDATA #IMPLIED
			instant CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED
			type CDATA #IMPLIED>

		<!ELEMENT effect (def|add|p_attack_trait|p_defence_trait|set|mul|div|sub|cond|triggers|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			interval CDATA #IMPLIED
			instant CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED
			type CDATA #IMPLIED>

		<!ELEMENT end_effect (def|add|p_attack_trait|p_defence_trait|set|mul|div|sub|cond|triggers|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST end_effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED>

			<!ELEMENT def (#PCDATA)>
			<!ATTLIST def
				name CDATA #REQUIRED
				value CDATA #REQUIRED>

		<!ELEMENT for (add|p_attack_trait|p_defence_trait|set|mul|div|sub|start_effect|tick_effect|self_effect|effect|end_effect)*>

			<!ELEMENT add (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST add
				order CDATA #IMPLIED
				stat CDATA #REQUIRED
				value CDATA #REQUIRED>

			<!ELEMENT p_attack_trait (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST p_attack_trait
				name CDATA #REQUIRED
				value CDATA #REQUIRED>

			<!ELEMENT p_defence_trait (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST p_defence_trait
				name CDATA #REQUIRED
				value CDATA #REQUIRED>

			<!ELEMENT mul (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST mul
				order CDATA #IMPLIED
				stat CDATA #REQUIRED
				value CDATA #REQUIRED>

			<!ELEMENT div (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST div
				order CDATA #IMPLIED
				stat CDATA #REQUIRED
				value CDATA #REQUIRED>

			<!ELEMENT sub (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST sub
				order CDATA #IMPLIED
				stat CDATA #REQUIRED
				value CDATA #REQUIRED>

		<!ELEMENT cond (player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST cond
			msgId CDATA #IMPLIED
			addName CDATA #IMPLIED>

			<!ELEMENT or (player|target|using|zone|has|game|or|not|and)*>

			<!ELEMENT not (player|target|using|zone|has|game|or|not|and)*>

			<!ELEMENT and (player|target|using|zone|has|game|or|not|and)*>

			<!ELEMENT player (#PCDATA)>
			<!ATTLIST player
				residence CDATA #IMPLIED
				olympiad CDATA #IMPLIED
				race CDATA #IMPLIED
				instance_zone CDATA #IMPLIED
				is_clan_leader CDATA #IMPLIED
				is_hero CDATA #IMPLIED
				sex CDATA #IMPLIED
				classId CDATA #IMPLIED
				minLevel CDATA #IMPLIED
				max_level CDATA #IMPLIED
				avail_max_sp CDATA #IMPLIED
				quest_state CDATA #IMPLIED
				min_pledge_rank CDATA #IMPLIED
				class_type CDATA #IMPLIED
				summon_siege_golem CDATA #IMPLIED
				running CDATA #IMPLIED
				percentHP CDATA #IMPLIED
				resting CDATA #IMPLIED
				max_level CDATA #IMPLIED
				maxPK CDATA #IMPLIED
				percentMP CDATA #IMPLIED
				moving CDATA #IMPLIED
				standing CDATA #IMPLIED
				damage CDATA #IMPLIED
				percentCP CDATA #IMPLIED
				direction CDATA #IMPLIED
				riding CDATA #IMPLIED
				flying CDATA #IMPLIED
				castle_type CDATA #IMPLIED
				chaos_festival CDATA #IMPLIED
				min_clan_level CDATA #IMPLIED
				has_abnormal_type CDATA #IMPLIED
				has_summon_id CDATA #IMPLIED
				can_transform CDATA #IMPLIED
				can_untransform CDATA #IMPLIED
				agathion CDATA #IMPLIED
				hasBuffId CDATA #IMPLIED
				flyingTransform CDATA #IMPLIED
				isFlagged CDATA #IMPLIED
				can_learn_skill CDATA #IMPLIED
				is_chaotic CDATA #IMPLIED
				has_vitality CDATA #IMPLIED>

			<!ELEMENT target (#PCDATA)>
			<!ATTLIST target
				is_pet_feed CDATA #IMPLIED
				type CDATA #IMPLIED
				race CDATA #IMPLIED
				hasForbiddenSkill CDATA #IMPLIED
				mobId CDATA #IMPLIED
				npc_class CDATA #IMPLIED
				castledoor CDATA #IMPLIED
				direction CDATA #IMPLIED
				percentHP CDATA #IMPLIED
				has_abnormal_type CDATA #IMPLIED
				forbiddenClassIds CDATA #IMPLIED
				min_distance CDATA #IMPLIED
				hasBuffId CDATA #IMPLIED
				playerRace CDATA #IMPLIED>

			<!ELEMENT using (#PCDATA)>
			<!ATTLIST using
				slotitem CDATA #IMPLIED
				kind CDATA #IMPLIED
				armor CDATA #IMPLIED
				weapon CDATA #IMPLIED
				skill CDATA #IMPLIED>

			<!ELEMENT zone (#PCDATA)>
			<!ATTLIST zone
				type CDATA #IMPLIED
				name CDATA #IMPLIED>

			<!ELEMENT game (#PCDATA)>
			<!ATTLIST game
				night CDATA #IMPLIED>

			<!ELEMENT has (#PCDATA)>
			<!ATTLIST has
				skill CDATA #IMPLIED>

		<!ELEMENT triggers (trigger)*>
		<!ELEMENT trigger (cond|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST trigger
			id CDATA #IMPLIED
			level CDATA #IMPLIED
			sub_level CDATA #IMPLIED
			type CDATA #IMPLIED
			chance CDATA #IMPLIED
			cancel_effects_on_remove CDATA #IMPLIED
			increasing CDATA #IMPLIED
			delay CDATA #IMPLIED
			args CDATA #IMPLIED>

		<!ELEMENT enchant_info (table|enchant_tables)*>
		<!ATTLIST enchant_info
			type CDATA #REQUIRED
			name CDATA #IMPLIED
			available CDATA #IMPLIED>

			<!ELEMENT enchant_tables (table)*>
			<!ATTLIST enchant_tables
				skill_level CDATA #REQUIRED
				enchant_levels CDATA #REQUIRED
				available CDATA #IMPLIED>

		<!ELEMENT restoration (group)*>
		<!ATTLIST restoration
			level CDATA #REQUIRED
			sub_level CDATA #IMPLIED
			consume_item_id CDATA #IMPLIED
			consume_item_count CDATA #IMPLIED
			on_fail_message CDATA #IMPLIED>

			<!ELEMENT group (item)*>
			<!ATTLIST group
				chance CDATA #REQUIRED>

				<!ELEMENT item (#PCDATA)>
				<!ATTLIST item
					id CDATA #REQUIRED
					min_count CDATA #REQUIRED
					max_count CDATA #IMPLIED
					enchant_level CDATA #IMPLIED>

=== MaicoSautner/l2script-teste/dist/gameserver/data/skills/11400-11499.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skill.dtd">
<list>
	<skill id="11496" levels="2" name="Summoner Boss Penalty">
		<set name="icon" value="icon.skill0217"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTDONE"/>
		<set name="operate_type" value="A2"/>
	</skill>
	<skill id="11497" levels="1" name="Summoner - Individual Passive">
		<set name="icon" value="icon.skill0217"/>
		<set name="magicLevel" value="85"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTDONE"/>
		<set name="operate_type" value="A2"/>
	</skill>
	<skill id="11498" levels="1" name="Summoner - Individual">
		<set name="icon" value="icon.skill1543"/>
		<set name="reuseDelay" value="5000"/>
		<set name="hitTime" value="500"/>
		<set name="abnormal_time" value="5"/>
		<set name="abnormal_level" value="1"/>
		<set name="abnormal_type" value="summon_condition"/>
		<set name="magicLevel" value="85"/>
		<set name="magicType" value="ITEM"/>
		<!--
		Предположительно яраость пета и тригес скила виликое владение призывом	Уровень: 1; Описание: В течение 5 сек. увеличивает Физ. Атк., Маг. Атк., шанс Крит. Атк., силу Крит. Атк. на 10%.
		-->
		<set name="target" value="TARGET_ONE_SERVITOR"/>
		<set name="skillType" value="BUFF"/>
		<set name="operate_type" value="A2"/>
		<for>
			<effect>
				<mul stat="pAtk" value="1.1"/>
				<mul stat="mAtk" value="1.1"/>
				<add stat="pCritRate" value="10"/>
				<add stat="p_critical_damage_per" value="10"/>
			</effect>
		</for>
	</skill>
	<skill id="11499" levels="1" name="Heavy Hit">
		<set name="icon" value="icon.skill10317"/>
		<set name="reuseDelay" value="10000"/>
		<set name="coolTime" value="300"/>
		<set name="castRange" value="900"/>
		<set name="hitTime" value="2000"/>
		<set name="mp_consume" value="71"/>
		<set name="magicLevel" value="85"/>
		<set name="magicType" value="MAGIC"/>
		<set name="power" value="5000"/>
		<set name="target" value="TARGET_ONE"/>
		<set name="skillType" value="PDAM"/>
		<set name="operate_type" value="A2"/>
	</skill>
</list>

=== MaicoSautner/l2script-teste/dist/gameserver/data/skills/46800-46899.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skill.dtd">
<list>
	<skill id="46800" levels="6" name="Sayha\'s Ring">
		<set name="icon" value="BranchIcon.Icon.ring_of_sayhas_i00"/>
		<set name="reuseDelay" value="1000"/>
		<set name="hitTime" value="500"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="46801" levels="6" name="Maphr\'s Ring">
		<set name="icon" value="BranchIcon.Icon.ring_of_maphr_i00"/>
		<set name="reuseDelay" value="1000"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="46802" levels="6" name="Maphr\'s Ring">
		<set name="icon" value="BranchIcon.Icon.ring_of_maphr_i00"/>
		<set name="reuseDelay" value="1000"/>
		<set name="hitTime" value="500"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
</list>

=== MaicoSautner/l2script-teste/dist/gameserver/data/skills/10600-10699.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skill.dtd">
<list>
	<skill id="10606" levels="1" name="Gust Movement">
		<table name="#pDef">1</table>
		<table name="#mDef">1</table>
		<set name="icon" value="icon.skill11862"/>
		<set name="reuseDelay" value="60000"/>
		<set name="coolTime" value="500"/>
		<set name="hitTime" value="1000"/>
		<set name="mp_consume" value="38"/>
		<set name="abnormal_time" value="5"/>
		<set name="magicLevel" value="99"/>
		<set name="magicType" value="ITEM"/>
		<set name="operate_type" value="A2"/>
		<set name="skillType" value="BUFF"/>
		<set name="target" value="TARGET_SELF"/>
		<cond msgId="113" addName="1">
			<using kind="Dagger,Dual Dagger"/>
		</cond>
		<enchant_info type="1" name="Shield">
			<enchant_tables skill_level="1" enchant_levels="20">
				<table name="#pDef">1.01 1.014 1.018 1.022 1.026 1.03 1.034 1.038 1.042 1.046 1.05 1.054 1.058 1.062 1.066 1.07 1.074 1.078 1.082 1.086</table>
			</enchant_tables>
		</enchant_info>
		<enchant_info type="2" name="Magic Shield">
			<enchant_tables skill_level="1" enchant_levels="20">
			<table name="#mDef">1.01 1.014 1.018 1.022 1.026 1.03 1.034 1.038 1.042 1.046 1.05 1.054 1.058 1.062 1.066 1.07 1.074 1.078 1.082 1.086</table>
			</enchant_tables>
		</enchant_info>
		<for>
			<effect>
				<add stat="pSkillEvasion" value="90"/>
				<mul stat="pDef" value="#pDef"/>
				<mul stat="mDef" value="#mDef"/>
			</effect>
		</for>
	</skill>
	<skill id="10607" levels="1" name="Maximum Mortality">
		<set name="icon" value="icon.skill10607"/>
		<set name="reuseDelay" value="300000"/>
		<set name="coolTime" value="500"/>
		<set name="hitTime" value="1000"/>
		<set name="mp_consume" value="38"/>
		<set name="abnormal_time" value="60"/>
		<set name="lethal2DepensencyAddon" value="20"/>
		<set name="lethal2SkillDepencensyAddon" value="10607"/>
		<set name="magicLevel" value="99"/>
		<set name="magicType" value="ITEM"/>
		<set name="operate_type" value="A2"/>
		<set name="skillType" value="BUFF"/>
		<set name="target" value="TARGET_SELF"/>
		<cond msgId="113" addName="1">
			<using kind="Dagger,Dual Dagger"/>
		</cond>
		<for>
			<effect>
				<mul stat="pAtkSpd" value="1.0"/>
			</effect>
		</for>
	</skill>
	<skill id="10608" levels="4" name="Superior Haste">
		<table name="#magicLevel">85 90 95 99</table>
		<table name="#reuse">0.95 0.94 0.93 0.9</table>
		<table name="#bld">10 11 13 15</table>
		<set name="icon" value="icon.skill10608"/>
		<set name="magicLevel" value="#magicLevel"/>
		<set name="operate_type" value="P"/>
		<for>
			<mul stat="mReuse" value="#reuse"/>
			<mul stat="pReuse" value="#reuse"/>
			<p_attack_trait name="bleed" value="#bld"/>
		</for>
	</skill>
	<skill id="10609" levels="1" name="Critical Chances">
		<table name="#TabrunSpd">0</table>
		<table name="#abnormal_time">300</table>
		<set name="icon" value="icon.skill10878"/>
		<set name="reuseDelay" value="290000"/>
		<set name="hitTime" value="2000"/>
		<set name="mp_consume" value="36"/>
		<set name="ride_state" value="NONE"/>
		<set name="abnormal_time" value="#abnormal_time"/>
		<set name="abnormal_level" value="1"/>
		<set name="abnormal_type" value="focus_dagger"/>
		<set name="magicLevel" value="85"/>
		<set name="hitCancelTime" value="500"/>
		<set name="effectPoint" value="669"/>
		<set name="target" value="TARGET_SELF"/>
		<set name="skillType" value="BUFF"/>
		<set name="operate_type" value="A2"/>
		<cond msgId="113">
			<using kind="Dagger,Dual Dagger"/>
		</cond>
		<enchant_info type="1" name="Time">
			<enchant_tables skill_level="1" enchant_levels="20">
				<table name="#abnormal_time" type="ADD">15 30 45 60 75 90 105 120 135 150 165 180 195 210 225 240 255 270 285 300</table>
			</enchant_tables>
		</enchant_info>
		<enchant_info type="2" name="Wind">
			<enchant_tables skill_level="1" enchant_levels="20">
				<table name="#TabrunSpd" type="ADD">2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40</table>
			</enchant_tables>
		</enchant_info>
		<for>
			<effect>
				<sub stat="p_critical_damage_per" value="30">
					<target direction="front"/>
				</sub>
				<!--<sub stat="pCritRate" value="30">
					<target direction="front"/>
				</sub>-->
				<add stat="p_critical_damage_per" value="65">
					<target direction="side"/>
				</add>
				<add stat="pCritRate" value="65">
					<target direction="side"/>
				</add>
				<add stat="p_critical_damage_per" value="50">
					<target direction="behind"/>
				</add>
				<add stat="pCritRate" value="50">
					<target direction="behind"/>
				</add>
				<mul stat="blowRate" value="1.15"/>
				<add stat="p_critical_damage_diff" value="304"/>
				<add stat="runSpd" value="#TabrunSpd"/>
			</effect>
		</for>
	</skill>
	<skill id="10610" levels="1" name="Critical Expansions">
		<set name="icon" value="icon.skill0819"/>
		<set name="magicLevel" value="85"/>
		<set name="operate_type" value="P"/>
		<for>
			<mul stat="p_crit_rate_limit" value="1.1">
				<using kind="Dagger,Dual Dagger"/>
			</mul>
		</for>
	</skill>
	<skill id="10653" levels="1" name="Shadow Evasion">
		<table name="#pDef">1</table>
		<table name="#mDef">1</table>
		<set name="icon" value="icon.skill5242"/>
		<set name="reuseDelay" value="60000"/>
		<set name="coolTime" value="500"/>
		<set name="hitTime" value="1000"/>
		<set name="mp_consume" value="38"/>
		<set name="abnormal_level" value="1"/>
		<set name="abnormal_time" value="10"/>
		<set name="abnormal_type" value="avoid_skill_special"/>
		<set name="magicLevel" value="85"/>
		<set name="operate_type" value="A2"/>
		<set name="skillType" value="BUFF"/>
		<set name="target" value="TARGET_SELF"/>
		<enchant_info type="1" name="Shield">
			<enchant_tables skill_level="1" enchant_levels="20">
				<table name="#pDef">1.01 1.014 1.018 1.022 1.026 1.03 1.034 1.038 1.042 1.046 1.05 1.054 1.058 1.062 1.066 1.07 1.074 1.078 1.082 1.086</table>
			</enchant_tables>
		</enchant_info>
		<enchant_info type="2" name="Magic Shield">
			<enchant_tables skill_level="1" enchant_levels="20">
				<table name="#mDef">1.01 1.014 1.018 1.022 1.026 1.03 1.034 1.038 1.042 1.046 1.05 1.054 1.058 1.062 1.066 1.07 1.074 1.078 1.082 1.086</table>
			</enchant_tables>
		</enchant_info>
		<for>
			<effect>
				<add stat="reflectPSkillDam" value="50"/> <!--maybe more or less? !-->
				<mul stat="pDef" value="#pDef"/>
				<mul stat="mDef" value="#mDef"/>
			</effect>
			<effect name="p_block_debuff"/>
		</for>
	</skill>
	<skill id="10654" levels="1" name="Maximum Mortality">
		<set name="icon" value="icon.skill10607"/>
		<set name="reuseDelay" value="300000"/>
		<set name="coolTime" value="500"/>
		<set name="hitTime" value="1000"/>
		<set name="mp_consume" value="38"/>
		<set name="abnormal_time" value="60"/>
		<set name="lethal2DepensencyAddon" value="20"/>
		<set name="lethal2SkillDepencensyAddon" value="10654"/>
		<set name="magicLevel" value="85"/>
		<set name="magicType" value="ITEM"/>
		<set name="operate_type" value="A2"/>
		<set name="skillType" value="BUFF"/>
		<set name="target" value="TARGET_SELF"/>
		<cond msgId="113" addName="1">
			<using kind="Dagger,Dual Dagger"/>
		</cond>
		<for>
			<effect>
				<mul stat="pAtkSpd" value="1.0"/><!--WTF?-->
			</effect>
		</for>
	</skill>
	<skill id="10655" levels="4" name="Brutal Stab Expert">
		<table name="#p_critical_damage_per">5 6 7 10</table>
		<table name="#magicLevel">85 90 95 99</table>
		<table name="#atk">1.05 1.06 1.07 1.1</table>
		<set name="icon" value="icon.skill10655"/>
		<set name="magicLevel" value="#magicLevel"/>
		<set name="operate_type" value="P"/>
		<for>
			<add stat="p_critical_damage_per" value="#p_critical_damage_per"/>
			<mul stat="pAtk" value="#atk"/>
		</for>
	</skill>
	<skill id="10656" levels="1" name="Shadow Hunter">
		<table name="#TabrunSpd">0</table>
		<table name="#abnormal_time">300</table>
		<set name="icon" value="icon.skill10656"/>
		<set name="reuseDelay" value="290000"/>
		<set name="hitTime" value="2000"/>
		<set name="mp_consume" value="36"/>
		<set name="ride_state" value="NONE"/>
		<set name="abnormal_time" value="300"/>
		<set name="abnormal_level" value="1"/>
		<set name="abnormal_type" value="focus_dagger"/>
		<set name="magicLevel" value="85"/>
		<set name="hitCancelTime" value="500"/>
		<set name="effectPoint" value="669"/>
		<set name="target" value="TARGET_SELF"/>
		<set name="skillType" value="BUFF"/>
		<set name="operate_type" value="A2"/>
		<cond msgId="113">
			<using kind="Dagger,Dual Dagger"/>
		</cond>
		<enchant_info type="1" name="Time">
			<enchant_tables skill_level="1" enchant_levels="20">
				<table name="#abnormal_time" type="ADD">15 30 45 60 75 90 105 120 135 150 165 180 195 210 225 240 255 270 285 300</table>
			</enchant_tables>
		</enchant_info>
		<enchant_info type="2" name="Wind">
			<enchant_tables skill_level="1" enchant_levels="20">
				<table name="#TabrunSpd" type="ADD">2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40</table>
			</enchant_tables>
		</enchant_info>
		<for>
			<effect>
				<sub stat="p_critical_damage_per" value="30">
					<target direction="front"/>
				</sub>
				<add stat="pCritRate" value="30">
					<target direction="side"/>
				</add>
				<add stat="p_critical_damage_per" value="30">
					<target direction="side"/>
				</add>
				<add stat="pCritRate" value="50">
					<target direction="behind"/>
				</add>
				<add stat="p_critical_damage_per" value="65">
					<target direction="behind"/>
				</add>
				<mul stat="blowRate" value="1.05"/>
				<add stat="p_critical_damage_diff" value="608"/>
				<add stat="runSpd" value="#TabrunSpd"/>
			</effect>
		</for>
	</skill>
</list>
