=== MaicoSautner/l2script-teste/dist/gameserver/data/skills/skill.dtd
<!ELEMENT list (skill)*>

	<!ELEMENT skill  (set|table|for|cond|triggers|enchant_info|restoration)*>
	<!ATTLIST skill
		id CDATA #REQUIRED
		levels CDATA #REQUIRED
		name CDATA #REQUIRED>

		<!ELEMENT set (player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST set
			name CDATA #IMPLIED
			order CDATA #IMPLIED
			stat CDATA #IMPLIED
			value CDATA #REQUIRED>

		<!ELEMENT table (#PCDATA)>
		<!ATTLIST table
			name CDATA #REQUIRED
			type CDATA #IMPLIED>

		<!ELEMENT start_effect (def|add|p_attack_trait|p_defence_trait|set|mul|div|sub|cond|triggers|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST start_effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			interval CDATA #IMPLIED
			instant CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED>

		<!ELEMENT tick_effect (def|add|p_attack_trait|p_defence_trait|set|mul|div|sub|cond|triggers|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST tick_effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			interval CDATA #IMPLIED
			instant CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED>

		<!ELEMENT self_effect (def|add|p_attack_trait|p_defence_trait|set|mul|div|sub|cond|triggers|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST self_effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			interval CDATA #IMPLIED
			instant CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED
			type CDATA #IMPLIED>

		<!ELEMENT effect (def|add|p_attack_trait|p_defence_trait|set|mul|div|sub|cond|triggers|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			interval CDATA #IMPLIED
			instant CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED
			type CDATA #IMPLIED>

		<!ELEMENT end_effect (def|add|p_attack_trait|p_defence_trait|set|mul|div|sub|cond|triggers|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST end_effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED>

			<!ELEMENT def (#PCDATA)>
			<!ATTLIST def
				name CDATA #REQUIRED
				value CDATA #REQUIRED>

		<!ELEMENT for (add|p_attack_trait|p_defence_trait|set|mul|div|sub|start_effect|tick_effect|self_effect|effect|end_effect)*>

			<!ELEMENT add (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST add
				order CDATA #IMPLIED
				stat CDATA #REQUIRED
				value CDATA #REQUIRED>

			<!ELEMENT p_attack_trait (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST p_attack_trait
				name CDATA #REQUIRED
				value CDATA #REQUIRED>

			<!ELEMENT p_defence_trait (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST p_defence_trait
				name CDATA #REQUIRED
				value CDATA #REQUIRED>

			<!ELEMENT mul (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST mul
				order CDATA #IMPLIED
				stat CDATA #REQUIRED
				value CDATA #REQUIRED>

			<!ELEMENT div (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST div
				order CDATA #IMPLIED
				stat CDATA #REQUIRED
				value CDATA #REQUIRED>

			<!ELEMENT sub (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST sub
				order CDATA #IMPLIED
				stat CDATA #REQUIRED
				value CDATA #REQUIRED>

		<!ELEMENT cond (player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST cond
			msgId CDATA #IMPLIED
			addName CDATA #IMPLIED>

			<!ELEMENT or (player|target|using|zone|has|game|or|not|and)*>

			<!ELEMENT not (player|target|using|zone|has|game|or|not|and)*>

			<!ELEMENT and (player|target|using|zone|has|game|or|not|and)*>

			<!ELEMENT player (#PCDATA)>
			<!ATTLIST player
				residence CDATA #IMPLIED
				olympiad CDATA #IMPLIED
				race CDATA #IMPLIED
				instance_zone CDATA #IMPLIED
				is_clan_leader CDATA #IMPLIED
				is_hero CDATA #IMPLIED
				sex CDATA #IMPLIED
				classId CDATA #IMPLIED
				minLevel CDATA #IMPLIED
				max_level CDATA #IMPLIED
				avail_max_sp CDATA #IMPLIED
				quest_state CDATA #IMPLIED
				min_pledge_rank CDATA #IMPLIED
				class_type CDATA #IMPLIED
				summon_siege_golem CDATA #IMPLIED
				running CDATA #IMPLIED
				percentHP CDATA #IMPLIED
				resting CDATA #IMPLIED
				max_level CDATA #IMPLIED
				maxPK CDATA #IMPLIED
				percentMP CDATA #IMPLIED
				moving CDATA #IMPLIED
				standing CDATA #IMPLIED
				damage CDATA #IMPLIED
				percentCP CDATA #IMPLIED
				direction CDATA #IMPLIED
				riding CDATA #IMPLIED
				flying CDATA #IMPLIED
				castle_type CDATA #IMPLIED
				chaos_festival CDATA #IMPLIED
				min_clan_level CDATA #IMPLIED
				has_abnormal_type CDATA #IMPLIED
				has_summon_id CDATA #IMPLIED
				can_transform CDATA #IMPLIED
				can_untransform CDATA #IMPLIED
				agathion CDATA #IMPLIED
				hasBuffId CDATA #IMPLIED
				flyingTransform CDATA #IMPLIED
				isFlagged CDATA #IMPLIED
				can_learn_skill CDATA #IMPLIED
				is_chaotic CDATA #IMPLIED
				has_vitality CDATA #IMPLIED>

			<!ELEMENT target (#PCDATA)>
			<!ATTLIST target
				is_pet_feed CDATA #IMPLIED
				type CDATA #IMPLIED
				race CDATA #IMPLIED
				hasForbiddenSkill CDATA #IMPLIED
				mobId CDATA #IMPLIED
				npc_class CDATA #IMPLIED
				castledoor CDATA #IMPLIED
				direction CDATA #IMPLIED
				percentHP CDATA #IMPLIED
				has_abnormal_type CDATA #IMPLIED
				forbiddenClassIds CDATA #IMPLIED
				min_distance CDATA #IMPLIED
				hasBuffId CDATA #IMPLIED
				playerRace CDATA #IMPLIED>

			<!ELEMENT using (#PCDATA)>
			<!ATTLIST using
				slotitem CDATA #IMPLIED
				kind CDATA #IMPLIED
				armor CDATA #IMPLIED
				weapon CDATA #IMPLIED
				skill CDATA #IMPLIED>

			<!ELEMENT zone (#PCDATA)>
			<!ATTLIST zone
				type CDATA #IMPLIED
				name CDATA #IMPLIED>

			<!ELEMENT game (#PCDATA)>
			<!ATTLIST game
				night CDATA #IMPLIED>

			<!ELEMENT has (#PCDATA)>
			<!ATTLIST has
				skill CDATA #IMPLIED>

		<!ELEMENT triggers (trigger)*>
		<!ELEMENT trigger (cond|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST trigger
			id CDATA #IMPLIED
			level CDATA #IMPLIED
			sub_level CDATA #IMPLIED
			type CDATA #IMPLIED
			chance CDATA #IMPLIED
			cancel_effects_on_remove CDATA #IMPLIED
			increasing CDATA #IMPLIED
			delay CDATA #IMPLIED
			args CDATA #IMPLIED>

		<!ELEMENT enchant_info (table|enchant_tables)*>
		<!ATTLIST enchant_info
			type CDATA #REQUIRED
			name CDATA #IMPLIED
			available CDATA #IMPLIED>

			<!ELEMENT enchant_tables (table)*>
			<!ATTLIST enchant_tables
				skill_level CDATA #REQUIRED
				enchant_levels CDATA #REQUIRED
				available CDATA #IMPLIED>

		<!ELEMENT restoration (group)*>
		<!ATTLIST restoration
			level CDATA #REQUIRED
			sub_level CDATA #IMPLIED
			consume_item_id CDATA #IMPLIED
			consume_item_count CDATA #IMPLIED
			on_fail_message CDATA #IMPLIED>

			<!ELEMENT group (item)*>
			<!ATTLIST group
				chance CDATA #REQUIRED>

				<!ELEMENT item (#PCDATA)>
				<!ATTLIST item
					id CDATA #REQUIRED
					min_count CDATA #REQUIRED
					max_count CDATA #IMPLIED
					enchant_level CDATA #IMPLIED>

=== MaicoSautner/l2script-teste/dist/gameserver/data/skills/18800-18899.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skill.dtd">
<list>
	<skill id="18814" levels="6" name="Topaz">
		<table name="#icon">icon.etc_bm_jewel_topaz_i00 icon.etc_bm_jewel_topaz_i00 icon.etc_bm_jewel_topaz_i00 icon.etc_bm_jewel_topaz_i00 icon.etc_bm_jewel_topaz_i00 icon.bm_jewel_absdmg_high_lv1_lavianrose</table>
		<set name="icon" value="#icon"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="18815" levels="6" name="Tanzanite">
		<table name="#icon">icon.etc_bm_jewel_tanzanite icon.etc_bm_jewel_tanzanite icon.etc_bm_jewel_tanzanite icon.etc_bm_jewel_tanzanite icon.etc_bm_jewel_tanzanite icon.bm_jewel_tanzanite_high_lv1_lavianrose</table>
		<set name="icon" value="#icon"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
</list>

=== MaicoSautner/l2script-teste/dist/gameserver/data/skills/8900-8999.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skill.dtd">
<list>
	<skill id="8900" levels="1" name="Dragon Fighter">
		<set name="icon" value="icon.skill5860"/>
		<set name="magicLevel" value="85"/>
		<set name="operate_type" value="P"/>
		<for>
			<mul stat="pvpPhysSkillDmgBonus" value="1.3"/>
			<mul stat="pvpPhysDmgBonus" value="1.3"/>
			<mul stat="pvpMagicSkillDmgBonus" value="1.3"/>
			<mul stat="maxHp" value="1.3"/>
			<mul stat="maxCp" value="1.3"/>
			<mul stat="maxMp" value="1.3"/>
			<add stat="max_hp_limit" value="50000"/><!--TODO: Check this.-->
			<add stat="max_mp_limit" value="50000"/><!--TODO: Check this.-->
			<add stat="max_cp_limit" value="50000"/><!--TODO: Check this.-->
			<mul stat="pAtkSpd" value="1.3"/>
			<add stat="basePCritRate" value="100"/>
			<add stat="p_skill_critical_damage_per" value="30"/>
			<mul stat="p_skill_power" value="1.3"/>
			<mul stat="pAtk" value="2">
				<target race="Dragons"/>
			</mul>
		</for>
	</skill>
	<skill id="8901" levels="1" name="Dragon Knight">
		<set name="icon" value="icon.skill5861"/>
		<set name="magicLevel" value="85"/>
		<set name="operate_type" value="P"/>
		<for>
			<mul stat="pvpPhysSkillDmgBonus" value="1.5"/>
			<mul stat="pvpPhysDmgBonus" value="1.5"/>
			<mul stat="pvpMagicSkillDmgBonus" value="1.5"/>
			<mul stat="maxHp" value="2"/>
			<mul stat="maxCp" value="2"/>
			<mul stat="maxMp" value="2"/>
			<add stat="max_hp_limit" value="50000"/><!--TODO: Check this.-->
			<add stat="max_mp_limit" value="50000"/><!--TODO: Check this.-->
			<add stat="max_cp_limit" value="50000"/><!--TODO: Check this.-->
			<mul stat="pAtkSpd" value="2"/>
			<add stat="basePCritRate" value="500"/>
			<add stat="p_skill_critical_damage_per" value="50"/>
			<mul stat="p_skill_power" value="1.5"/>
			<mul stat="pAtk" value="4">
				<target race="Dragons"/>
			</mul>
		</for>
	</skill>
	<skill id="8902" levels="1" name="Dragon Mage">
		<set name="icon" value="icon.skill5860"/>
		<set name="magicLevel" value="85"/>
		<set name="operate_type" value="P"/>
		<for>
			<mul stat="pvpPhysSkillDmgBonus" value="1.3"/>
			<mul stat="pvpPhysDmgBonus" value="1.3"/>
			<mul stat="pvpMagicSkillDmgBonus" value="1.3"/>
			<mul stat="maxHp" value="1.3"/>
			<mul stat="maxCp" value="1.3"/>
			<mul stat="maxMp" value="1.3"/>
			<add stat="max_hp_limit" value="50000"/><!--TODO: Check this.-->
			<add stat="max_mp_limit" value="50000"/><!--TODO: Check this.-->
			<add stat="max_cp_limit" value="50000"/><!--TODO: Check this.-->
			<mul stat="mAtkSpd" value="1.3"/>
			<add stat="baseMCritRate" value="100"/>
			<mul stat="mSkillPower" value="1.5"/>
			<mul stat="mAtk" value="2">
				<target race="Dragons"/>
			</mul>
		</for>
	</skill>
	<skill id="8903" levels="1" name="Dragon Wizard">
		<set name="icon" value="icon.skill5861"/>
		<set name="magicLevel" value="85"/>
		<set name="operate_type" value="P"/>
		<for>
			<mul stat="pvpPhysSkillDmgBonus" value="1.5"/>
			<mul stat="pvpPhysDmgBonus" value="1.5"/>
			<mul stat="pvpMagicSkillDmgBonus" value="1.5"/>
			<mul stat="maxHp" value="2"/>
			<mul stat="maxCp" value="2"/>
			<mul stat="maxMp" value="2"/>
			<add stat="max_hp_limit" value="50000"/><!--TODO: Check this.-->
			<add stat="max_mp_limit" value="50000"/><!--TODO: Check this.-->
			<add stat="max_cp_limit" value="50000"/><!--TODO: Check this.-->
			<mul stat="mAtkSpd" value="2"/>
			<add stat="baseMCritRate" value="500"/>
			<mul stat="mSkillPower" value="1.5"/>
			<add stat="mCritRate" value="50"/>
			<mul stat="mAtk" value="4">
				<target race="Dragons"/>
			</mul>
		</for>
	</skill>
	<skill id="8904" levels="1" name="Summon Eviscerator Fox">
		<set name="icon" value="icon.skill8904"/>
		<set name="hitTime" value="1000"/>
		<set name="olympiad_use" value="false"/>
		<set name="abnormal_time" value="3600"/>
		<set name="abnormal_level" value="1"/>
		<set name="abnormal_type" value="transform"/>
		<set name="magicType" value="SPECIAL"/>
		<set name="target" value="TARGET_SELF"/>
		<set name="skillType" value="BUFF"/>
		<set name="operate_type" value="A2"/>
		<set name="isSkillTimePermanent" value="true"/>
		<set name="hitCancelTime" value="500"/>
		<cond>
			<player can_transform="154"/>
		</cond>
		<for>
			<effect name="Transformation" value="154"/>
			<effect name="i_dispel_by_slot">
				<def name="abnormal_type" value="changebody"/>
				<def name="max_abnormal_level" value="-1"/>
			</effect>
			<effect name="i_dispel_by_slot">
				<def name="abnormal_type" value="turn_stone"/>
				<def name="max_abnormal_level" value="-1"/>
			</effect>
			<effect name="i_dispel_by_slot">
				<def name="abnormal_type" value="buff_special_multi"/>
				<def name="max_abnormal_level" value="-1"/>
			</effect>
		</for>
	</skill>
	<skill id="8905" levels="1" name="Summon Sayha\'s Seer Fox">
		<set name="icon" value="icon.skill8905"/>
		<set name="hitTime" value="1000"/>
		<set name="olympiad_use" value="false"/>
		<set name="abnormal_time" value="3600"/>
		<set name="abnormal_level" value="1"/>
		<set name="abnormal_type" value="transform"/>
		<set name="magicType" value="SPECIAL"/>
		<set name="target" value="TARGET_SELF"/>
		<set name="skillType" value="BUFF"/>
		<set name="operate_type" value="A2"/>
		<set name="isSkillTimePermanent" value="true"/>
		<set name="hitCancelTime" value="500"/>
		<cond>
			<player can_transform="155"/>
		</cond>
		<for>
			<effect name="Transformation" value="155"/>
			<effect name="i_dispel_by_slot">
				<def name="abnormal_type" value="changebody"/>
				<def name="max_abnormal_level" value="-1"/>
			</effect>
			<effect name="i_dispel_by_slot">
				<def name="abnormal_type" value="turn_stone"/>
				<def name="max_abnormal_level" value="-1"/>
			</effect>
			<effect name="i_dispel_by_slot">
				<def name="abnormal_type" value="buff_special_multi"/>
				<def name="max_abnormal_level" value="-1"/>
			</effect>
		</for>
	</skill>
	<skill id="8906" levels="1" name="Riding the Hell Hound">
		<set name="icon" value="icon.hellound_vehicle"/>
		<set name="hitTime" value="1000"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="8907" levels="1" name="Riding the Pegasus">
		<set name="icon" value="icon.pegasus_vehicle"/>
		<set name="hitTime" value="1000"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="8908" levels="1" name="Riding the Wing Hound">
		<set name="icon" value="icon.winghound_vehicle"/>
		<set name="hitTime" value="1000"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="8909" levels="1" name="Riding the War Horse">
		<set name="icon" value="icon.warhorse_vehicle"/>
		<set name="hitTime" value="1000"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="8910" levels="1" name="Riding the Griffin">
		<set name="icon" value="icon.griffin_vehicle"/>
		<set name="hitTime" value="1000"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
</list>

=== MaicoSautner/l2script-teste/dist/gameserver/data/skills/30600-30699.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skill.dtd">
<list>
	<skill id="30600" levels="1" name="Heavy Hit">
		<set name="icon" value="icon.skill0000"/>
		<set name="reuseDelay" value="10000"/>
		<set name="coolTime" value="500"/>
		<set name="castRange" value="600"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTDONE"/>
		<set name="operate_type" value="A2"/>
	</skill>
	<skill id="30601" levels="1" name="Heavy Hit">
		<set name="icon" value="icon.skill0000"/>
		<set name="reuseDelay" value="10000"/>
		<set name="coolTime" value="500"/>
		<set name="hitTime" value="2000"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTDONE"/>
		<set name="operate_type" value="A2"/>
	</skill>
	<skill id="30602" levels="1" name="Eviscerator Aura">
		<set name="icon" value="icon.icon_lender"/>
		<set name="reuseDelay" value="5000"/>
		<set name="magicLevel" value="85"/>
		<set name="operate_type" value="AU"/>
		<set name="target" value="TARGET_SELF"/>
		<for>
			<effect name="p_aura">
				<def name="id" value="30603"/>	<!--Eviscerator Aura-->
			</effect>
		</for>
	</skill>
	<skill id="30603" levels="1" name="Eviscerator Force">
		<set name="icon" value="icon.icon_lender_01"/>
		<set name="reuseDelay" value="5000"/>
		<set name="abnormal_time" value="11"/>
		<set name="abnormal_level" value="1"/>
		<set name="abnormal_type" value="synergy_ranger"/>
		<set name="magicLevel" value="85"/>
		<set name="magicType" value="MUSIC"/>
		<set name="operate_type" value="A6"/>
		<set name="skillType" value="BUFF"/>
		<set name="target" value="TARGET_PARTY"/>
		<set name="effectPoint" value="2"/>
		<set name="affect_range" value="1600"/>
		<for>
			<effect>
				<add stat="pCritRate" value="1"/>
			</effect>
		</for>
	</skill>
	<skill id="30604" levels="1" name="Block Eviscerator Force">
		<set name="icon" value="icon.icon_lender"/>
		<set name="magicLevel" value="85"/>
		<set name="target" value="TARGET_SELF"/>
		<set name="skillType" value="BUFF"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="30605" levels="1" name="Sayha\'s Seer Aura">
		<set name="icon" value="icon.icon_Er_wizard"/>
		<set name="reuseDelay" value="5000"/>
		<set name="magicLevel" value="85"/>
		<set name="operate_type" value="AU"/>
		<set name="target" value="TARGET_SELF"/>
		<for>
			<effect name="p_aura">
				<def name="id" value="30606"/>	<!--Sayha's Seer Aura-->
			</effect>
		</for>
	</skill>
	<skill id="30606" levels="1" name="Sayha\'s Seer Force">
		<set name="icon" value="icon.icon_Er_wizard_01"/>
		<set name="reuseDelay" value="5000"/>
		<set name="abnormal_time" value="11"/>
		<set name="abnormal_level" value="1"/>
		<set name="abnormal_type" value="synergy_ruler"/>
		<set name="magicLevel" value="85"/>
		<set name="magicType" value="MUSIC"/>
		<set name="operate_type" value="A6"/>
		<set name="skillType" value="BUFF"/>
		<set name="target" value="TARGET_PARTY"/>
		<set name="effectPoint" value="2"/>
		<set name="affect_range" value="1600"/>
		<for>
			<effect>
				<add stat="mCritRate" value="1"/>
			</effect>
		</for>
	</skill>
	<skill id="30607" levels="1" name="Block Sayha\'s Seer Force">
		<set name="icon" value="icon.icon_Er_wizard"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTDONE"/>
		<set name="operate_type" value="A2"/>
	</skill>
	<skill id="30608" levels="5" name="Fury of Eviscerator">
		<table name="#pAtk">1.05 1.1 1.15 1.2 </table>
		<table name="#p_attack_trait_knockdown">0 0 0 0 50</table>
		<set name="icon" value="icon.skill30509"/>
		<set name="hitTime" value="300"/>
		<set name="target" value="TARGET_SELF"/>
		<set name="abnormal_time" value="5"/>
		<set name="skillType" value="BUFF"/>
		<set name="operate_type" value="A2"/>
		<for>
			<effect>
				<mul stat="pAtk" value="#pAtk"/>
				<p_attack_trait name="knockdown" value="#p_attack_trait_knockdown"/>
			</effect>
		</for>
	</skill>
</list>

=== MaicoSautner/l2script-teste/dist/gameserver/data/skills/19400-19499.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skill.dtd">
<list>
	<skill id="19400" levels="3" name="Elemental Spike - Decrease Dark Resistance">
		<table name="#abnormal_time">7 7 15</table>
		<table name="#activateRate">100</table>
		<table name="#dispel_max_abnormal_lvl">9 0 0</table>
		<table name="#unholy">20 50 100</table>
		<set name="icon" value="icon.skill11011"/>
		<set name="abnormal_level" value="5"/>
		<set name="abnormal_time" value="#abnormal_time"/>
		<set name="abnormal_type" value="multi_debuff_fire"/>
		<set name="activateRate" value="#activateRate"/>
		<set name="magicLevel" value="85"/>
		<set name="magicType" value="ITEM"/>
		<set name="operate_type" value="A2"/>
		<set name="skillType" value="DEBUFF"/>
		<set name="target" value="TARGET_ONE"/>
		<for>
			<effect>
				<sub stat="defenceUnholy" value="#unholy"/>
			</effect>
			<effect name="i_dispel_by_slot">
				<def name="abnormal_type" value="multi_debuff_fire"/>
				<def name="max_abnormal_level" value="#dispel_max_abnormal_lvl"/>
			</effect>
			<effect name="i_dispel_by_slot">
				<def name="abnormal_type" value="multi_debuff_water"/>
				<def name="max_abnormal_level" value="#dispel_max_abnormal_lvl"/>
			</effect>
			<effect name="i_dispel_by_slot">
				<def name="abnormal_type" value="multi_debuff_wind"/>
				<def name="max_abnormal_level" value="#dispel_max_abnormal_lvl"/>
			</effect>
			<effect name="i_dispel_by_slot">
				<def name="abnormal_type" value="multi_debuff_earth"/>
				<def name="max_abnormal_level" value="#dispel_max_abnormal_lvl"/>
			</effect>
			<effect name="i_dispel_by_slot">
				<def name="abnormal_type" value="multi_debuff_holy"/>
				<def name="max_abnormal_level" value="#dispel_max_abnormal_lvl"/>
			</effect>
		</for>
	</skill>
	<skill id="19403" levels="3" name="Elemental Harmony">
		<set name="icon" value="icon.skill10044"/>
		<set name="mp_consume" value="70"/>
		<table name="#power">50 70 100</table>
		<table name="#abnormal_time">5 5 10</table>
		<set name="abnormal_time" value="#abnormal_time"/>
		<set name="skillType" value="BUFF_CHARGER"/>
		<set name="target" value="TARGET_SELF"/>
		<set name="operate_type" value="A2"/>
		<set name="isHideUseMessage" value="true"/>
		<for>
			<effect>
				<add stat="attackFire" value="#power"/>
				<add stat="attackWater" value="#power"/>
				<add stat="attackWind" value="#power"/>
				<add stat="attackEarth" value="#power"/>
			</effect>
		</for>
	</skill>
	<skill id="19404" levels="6" name="Fire Attribute">
		<set name="icon" value="icon.skill11046"/>
		<set name="mp_consume" value="70"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="19405" levels="4" name="Discarded Wizard\'s Soul">
		<table name="#mp_consume">483 495 507 519</table>
		<set name="icon" value="icon.skill19405"/>
		<set name="reuseDelay" value="5000"/>
		<set name="coolTime" value="500"/>
		<set name="hitTime" value="3500"/>
		<set name="mp_consume" value="#mp_consume"/>		
		<table name="#magicLevel">99 101 103 105</table>		
		<set name="ride_state" value="NONE;STRIDER;WYVERN;WOLF"/>
		<set name="magicLevel" value="#magicLevel"/>
		<set name="magicType" value="MAGIC"/>		
		<set name="target" value="TARGET_SELF"/>		
		<set name="skillType" value="SUMMON"/>
		<set name="operate_type" value="A2"/>
		<!-- Summon-specific -->
		<table name="#npcIds">15207 15208 15209 15210</table>
		<set name="npcId" value="#npcIds"/>
	</skill>
	<skill id="19406" levels="4" name="Curse from Deadland">
		<set name="icon" value="icon.action225"/>
		<set name="reuseDelay" value="5000"/>
		<set name="coolTime" value="500"/>
		<set name="hitTime" value="500"/>
		<set name="mp_consume" value="72"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="19407" levels="3" name="Essence of Mana">
		<set name="icon" value="icon.skill11034"/>
		<set name="mp_consume" value="36"/>
		<table name="#S">1.3 1.4 1.5</table>			
		<table name="#mCritRate">30 40 50</table>
		<set name="target" value="TARGET_SELF"/>
		<set name="operate_type" value="T"/>
		<for>
			<effect>
				<mul stat="mAtk" value="#S"/>
				<add stat="mCritRate" value="#mCritRate"/>				
				<mul stat="pDef" value="#S"/>				
			</effect>
		</for>
	</skill>
	<skill id="19408" levels="2" name="Embody Mana Armor">
		<set name="icon" value="icon.skill11065"/>
		<set name="reuseDelay" value="5000"/>
		<set name="mp_consume" value="36"/>
		<table name="#pshie">90 95</table>
		<set name="abnormal_effect" value="MP_SHIELD"/>		
		<set name="abnormal_type" value="mp_shield"/>
		<set name="target" value="TARGET_SELF"/>		
		<set name="operate_type" value="T"/>
		<for>			
			<effect name="AbsorbDamageToMp" interval="1" value="50"><!-- TO DOO 50 маны каждую сек-->
				<set order="0x10" stat="p_mp_shield" value="#pshie"/>
				<add order="0x40" stat="reflectDam" value="10"/>
				<add order="0x40" stat="reflectBowDam" value="10"/>
				<add order="0x40" stat="reflectPSkillDam" value="10"/>
				<add order="0x40" stat="reflectMSkillDam" value="10"/>				
			</effect>
		</for>
	</skill>
	<skill id="19409" levels="1" name="Curse Gloom">
		<set name="icon" value="icon.skill1263"/>		
		<set name="abnormal_level" value="1"/>
		<set name="abnormal_time" value="10"/>
		<set name="abnormal_type" value="md_down"/>		
		<set name="magicLevel" value="85"/>	
		<set name="magicType" value="MAGIC"/>		
		<set name="operate_type" value="A2"/>
		<set name="skillType" value="DEBUFF"/>
		<set name="target" value="TARGET_ONE"/>
		<for>
			<effect>
				<mul stat="mDef" value="0.5"/>
				<sub stat="defenceWater" value="50"/>
				<sub stat="defenceFire" value="50"/>
				<sub stat="defenceWind" value="50"/>
				<sub stat="defenceEarth" value="50"/>
				<sub stat="defenceHoly" value="50"/>
				<sub stat="defenceUnholy" value="50"/>
			</effect>
		</for>
	</skill>
	<skill id="19410" levels="1" name="Elemental Crash (Wind)">
		<set name="icon" value="icon.skill11018"/>
		<set name="reuseDelay" value="10000"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="19411" levels="1" name="Elemental Crash (Earth)">
		<set name="icon" value="icon.skill11018"/>
		<set name="reuseDelay" value="10000"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="19412" levels="1" name="Elemental Crash (Holy)">
		<set name="icon" value="icon.skill11018"/>
		<set name="reuseDelay" value="10000"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="19413" levels="7" name="Elemental Burst: Water">
		<set name="icon" value="icon.skill11865"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="19414" levels="7" name="Elemental Burst: Wind">
		<set name="icon" value="icon.skill11865"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="19415" levels="7" name="Elemental Burst: Earth">
		<set name="icon" value="icon.skill11865"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="19416" levels="7" name="Elemental Burst: Holy">
		<set name="icon" value="icon.skill11865"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="19417" levels="7" name="Elemental Burst: Water">
		<set name="icon" value="icon.skill11865"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="19418" levels="7" name="Elemental Burst: Wind">
		<set name="icon" value="icon.skill11865"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="19419" levels="7" name="Elemental Burst: Earth">
		<set name="icon" value="icon.skill11865"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="19420" levels="4" name="Quadruple Elemental Blast">
		<set name="icon" value="icon.skill11067"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
</list>
